CREATE TABLE GUEST (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    FULLNAME VARCHAR(50),
    PHONE VARCHAR(50) UNIQUE,
    PRIMARY KEY (ID)
 );

CREATE TABLE PARCEL (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    LOCATION VARCHAR(10) UNIQUE,
    ELECTRICITY BOOLEAN,
    WATER BOOLEAN,
    PRIMARY KEY (ID)
 );

CREATE TABLE RESERVATION (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    DATEFROM DATE,
    DATETO DATE,
    PARCEL BIGINT,
    GUEST BIGINT,
    PRIMARY KEY (ID)
--    FOREIGN KEY (PARCEL) REFERENCES PARCEL(ID),
--    FOREIGN KEY (GUEST) REFERENCES GUEST(ID)
 );
