/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.project.autocamp.gui;

import com.toedter.calendar.JDateChooser;
import cz.muni.fi.pv168.project.autocamp.DBInteractionException;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Administrator
 */
public class AutoCampMenu extends javax.swing.JFrame {

    public static JOptionPane jOptionPane;
    public static final Logger logger = LoggerFactory.getLogger(AutoCampMenu.class);

    /**
     * Creates new form AutoCampMenu
     */
    public AutoCampMenu() {
        initComponents();
        GuestsTableModel guestsModel = (GuestsTableModel) guestTable.getModel();
        ParcelsTableModel parcelsModel = (ParcelsTableModel) parcelTable.getModel();
        ReservationsTableModel reservationsModel = (ReservationsTableModel) reservationTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        reservationsButton = new javax.swing.JButton();
        guestsButton = new javax.swing.JButton();
        parcelsButton = new javax.swing.JButton();
        autocampTabbedPane = new javax.swing.JTabbedPane();
        guestsTab = new javax.swing.JPanel();
        guestTablePanel = new javax.swing.JScrollPane();
        guestTable = new javax.swing.JTable();
        guestCreateButton = new javax.swing.JButton();
        guestPhoneField = new javax.swing.JTextField();
        guestFullNameField = new javax.swing.JTextField();
        guestFullNameLabel = new javax.swing.JLabel();
        guestPhoneLabel = new javax.swing.JLabel();
        guestFilterButton = new javax.swing.JButton();
        guestDeleteButton = new javax.swing.JButton();
        guestFilterField = new javax.swing.JTextField();
        guestFilterLabel = new javax.swing.JLabel();
        parcelsTab = new javax.swing.JPanel();
        parcelTablePanel = new javax.swing.JScrollPane();
        parcelTable = new javax.swing.JTable();
        parcelCreateButton = new javax.swing.JButton();
        parcelLocationField = new javax.swing.JTextField();
        parcelLocationLabel = new javax.swing.JLabel();
        parcelElectricityCheckBox = new javax.swing.JCheckBox();
        parcelWaterCheckBox = new javax.swing.JCheckBox();
        parcelResourcesLabel = new javax.swing.JLabel();
        parcelFilterLabel = new javax.swing.JLabel();
        parcelFilterField = new javax.swing.JTextField();
        parcelFilterButton = new javax.swing.JButton();
        parcelDeleteButton = new javax.swing.JButton();
        Reservations = new javax.swing.JPanel();
        reservationsScrollPane = new javax.swing.JScrollPane();
        reservationTable = new javax.swing.JTable();
        reservationsCreateButton = new javax.swing.JButton();
        reservationsFromLabel = new javax.swing.JLabel();
        reservationsToLabel = new javax.swing.JLabel();
        reservationsDateFromChooser = new com.toedter.calendar.JDateChooser();
        reservationsDateToChooser = new com.toedter.calendar.JDateChooser();
        reservationParcelLabel = new javax.swing.JLabel();
        reservationParcelField = new javax.swing.JTextField();
        reservationFilterLabel = new javax.swing.JLabel();
        reservationFilterField = new javax.swing.JTextField();
        reservationFilterButton = new javax.swing.JButton();
        reservationDeleteButton = new javax.swing.JButton();
        reservationGuestField = new javax.swing.JTextField();
        reservationGuestLabel = new javax.swing.JLabel();
        reservationParcelButton = new javax.swing.JButton();
        reservationGuestButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        leftPanel.setBackground(new java.awt.Color(204, 204, 204));
        leftPanel.setFocusable(false);
        leftPanel.setMaximumSize(new java.awt.Dimension(207, 32767));

        reservationsButton.setBackground(new java.awt.Color(255, 255, 255));
        reservationsButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        reservationsButton.setText(LocalizationWizard.getString("Reservations"));
        reservationsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationsButtonMouseClicked(evt);
            }
        });

        guestsButton.setBackground(new java.awt.Color(255, 255, 255));
        guestsButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        guestsButton.setText(LocalizationWizard.getString("Guests"));
        guestsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guestsButtonMouseClicked(evt);
            }
        });

        parcelsButton.setBackground(new java.awt.Color(255, 255, 255));
        parcelsButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        parcelsButton.setText(LocalizationWizard.getString("Parcels"));
        parcelsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parcelsButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservationsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guestsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parcelsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parcelsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(leftPanel);

        autocampTabbedPane.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        autocampTabbedPane.setToolTipText("");

        guestTable.setModel(new GuestsTableModel() );
        guestTablePanel.setViewportView(guestTable);

        guestCreateButton.setText(LocalizationWizard.getString("Create"));
        guestCreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guestCreateButtonMouseClicked(evt);
            }
        });
        guestCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestCreateButtonActionPerformed(evt);
            }
        });

        guestFullNameLabel.setText(LocalizationWizard.getString("Full_name")+":");

        guestPhoneLabel.setText(LocalizationWizard.getString("Phone")+":");

        guestFilterButton.setText(LocalizationWizard.getString("Filter"));
        guestFilterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guestFilterButtonMouseClicked(evt);
            }
        });

        guestDeleteButton.setText(LocalizationWizard.getString("Delete_selected"));
        guestDeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guestDeleteButtonMouseClicked(evt);
            }
        });

        guestFilterLabel.setText(LocalizationWizard.getString("Filter_label")+":");

        javax.swing.GroupLayout guestsTabLayout = new javax.swing.GroupLayout(guestsTab);
        guestsTab.setLayout(guestsTabLayout);
        guestsTabLayout.setHorizontalGroup(
            guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guestTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
            .addGroup(guestsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(guestFilterLabel)
                        .addComponent(guestPhoneLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(guestFullNameLabel))
                .addGap(18, 18, 18)
                .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guestPhoneField)
                    .addGroup(guestsTabLayout.createSequentialGroup()
                        .addComponent(guestFilterField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guestFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(guestFullNameField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guestDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guestCreateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        guestsTabLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {guestFilterLabel, guestPhoneLabel});

        guestsTabLayout.setVerticalGroup(
            guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guestsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(guestsTabLayout.createSequentialGroup()
                        .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guestFullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guestFullNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guestPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guestPhoneLabel)))
                    .addComponent(guestCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(guestFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(guestFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(guestFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(guestDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guestTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE))
        );

        autocampTabbedPane.addTab("Guest", guestsTab);

        parcelTable.setModel(new ParcelsTableModel());
        parcelTablePanel.setViewportView(parcelTable);

        parcelCreateButton.setText(LocalizationWizard.getString("Create"));
        parcelCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcelCreateButtonActionPerformed(evt);
            }
        });

        parcelLocationLabel.setText(LocalizationWizard.getString("Location")+":");

        parcelElectricityCheckBox.setText(LocalizationWizard.getString("Electricity"));

        parcelWaterCheckBox.setText(LocalizationWizard.getString("Water"));

        parcelResourcesLabel.setText(LocalizationWizard.getString("Resources")+":");

        parcelFilterLabel.setText(LocalizationWizard.getString("Filter_label"));

        parcelFilterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcelFilterFieldActionPerformed(evt);
            }
        });

        parcelFilterButton.setText(LocalizationWizard.getString("Filter"));
        parcelFilterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parcelFilterButtonMouseClicked(evt);
            }
        });
        parcelFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcelFilterButtonActionPerformed(evt);
            }
        });

        parcelDeleteButton.setText(LocalizationWizard.getString("Delete_selected"));
        parcelDeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parcelDeleteButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout parcelsTabLayout = new javax.swing.GroupLayout(parcelsTab);
        parcelsTab.setLayout(parcelsTabLayout);
        parcelsTabLayout.setHorizontalGroup(
            parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parcelTablePanel)
            .addGroup(parcelsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parcelLocationLabel)
                    .addComponent(parcelResourcesLabel)
                    .addComponent(parcelFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parcelsTabLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(parcelElectricityCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(parcelWaterCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parcelsTabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(parcelLocationField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parcelsTabLayout.createSequentialGroup()
                                .addComponent(parcelFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(parcelFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(parcelCreateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(parcelDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        parcelsTabLayout.setVerticalGroup(
            parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parcelsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parcelCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(parcelsTabLayout.createSequentialGroup()
                        .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parcelLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parcelLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parcelResourcesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parcelElectricityCheckBox)
                            .addComponent(parcelWaterCheckBox))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parcelFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(parcelDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(parcelFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(parcelFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parcelTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE))
        );

        autocampTabbedPane.addTab("Parcels", parcelsTab);

        reservationTable.setModel(new ReservationsTableModel());
        reservationsScrollPane.setViewportView(reservationTable);

        reservationsCreateButton.setText(LocalizationWizard.getString("Create"));
        reservationsCreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationsCreateButtonMouseClicked(evt);
            }
        });
        reservationsCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationsCreateButtonActionPerformed(evt);
            }
        });

        reservationsFromLabel.setText(LocalizationWizard.getString("From")+":");

        reservationsToLabel.setText(LocalizationWizard.getString("To")+":");

        reservationsDateFromChooser.setDateFormatString("yyyy-MM-dd");

        reservationsDateToChooser.setDateFormatString("yyyy-MM-dd");

        reservationParcelLabel.setText(LocalizationWizard.getString("Parcel")+":");

        reservationParcelField.setEnabled(false);
        reservationParcelField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationParcelFieldMouseClicked(evt);
            }
        });

        reservationFilterLabel.setText(LocalizationWizard.getString("Filter_label")+":");

        reservationFilterButton.setText(LocalizationWizard.getString("Filter"));
        reservationFilterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationFilterButtonMouseClicked(evt);
            }
        });

        reservationDeleteButton.setText(LocalizationWizard.getString("Delete_selected"));
        reservationDeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationDeleteButtonMouseClicked(evt);
            }
        });

        reservationGuestField.setEnabled(false);

        reservationGuestLabel.setText(LocalizationWizard.getString("Guest")+":");

        reservationParcelButton.setText("...");
        reservationParcelButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        reservationParcelButton.setMaximumSize(new java.awt.Dimension(25, 19));
        reservationParcelButton.setMinimumSize(new java.awt.Dimension(25, 19));
        reservationParcelButton.setPreferredSize(new java.awt.Dimension(25, 19));
        reservationParcelButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        reservationParcelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationParcelButtonMouseClicked(evt);
            }
        });

        reservationGuestButton.setText("...");
        reservationGuestButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        reservationGuestButton.setMaximumSize(new java.awt.Dimension(20, 19));
        reservationGuestButton.setMinimumSize(new java.awt.Dimension(20, 19));
        reservationGuestButton.setPreferredSize(new java.awt.Dimension(20, 19));
        reservationGuestButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        reservationGuestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationGuestButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ReservationsLayout = new javax.swing.GroupLayout(Reservations);
        Reservations.setLayout(ReservationsLayout);
        ReservationsLayout.setHorizontalGroup(
            ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ReservationsLayout.createSequentialGroup()
                        .addComponent(reservationFilterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(reservationFilterField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservationFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ReservationsLayout.createSequentialGroup()
                        .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ReservationsLayout.createSequentialGroup()
                                .addComponent(reservationParcelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(reservationParcelField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reservationParcelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reservationGuestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ReservationsLayout.createSequentialGroup()
                                .addComponent(reservationsFromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(reservationsDateFromChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reservationsToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reservationsDateToChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservationsLayout.createSequentialGroup()
                                .addComponent(reservationGuestField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reservationGuestButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservationsCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservationDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(reservationsScrollPane)
        );

        ReservationsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {reservationFilterLabel, reservationParcelLabel, reservationsFromLabel});

        ReservationsLayout.setVerticalGroup(
            ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReservationsLayout.createSequentialGroup()
                        .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reservationsDateFromChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservationsDateToChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservationsToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReservationsLayout.createSequentialGroup()
                                .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(reservationGuestField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reservationGuestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reservationParcelField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reservationParcelLabel))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(reservationParcelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservationsLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(reservationGuestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(reservationsFromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservationsCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reservationFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservationFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservationFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservationDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reservationsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE))
        );

        autocampTabbedPane.addTab("Reservations", Reservations);

        getContentPane().add(autocampTabbedPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parcelCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcelCreateButtonActionPerformed
        try {
            ((ParcelsTableModel) parcelTable.getModel()).createParcel(
                    parcelLocationField.getText(),
                    parcelElectricityCheckBox.isSelected(),
                    parcelWaterCheckBox.isSelected());
            parcelLocationField.setText(null);
            parcelElectricityCheckBox.setSelected(false);
            parcelWaterCheckBox.setSelected(false);
        } catch (ExecutionException | InterruptedException ex) {
            AutoCampMenu.jOptionPane.showMessageDialog(this, LocalizationWizard.getString("Create_parcel")
                    + LocalizationWizard.getString("Log_file_info"));
            logger.error(ex.getMessage());
        }
    }//GEN-LAST:event_parcelCreateButtonActionPerformed

    private void guestsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestsButtonMouseClicked
        autocampTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_guestsButtonMouseClicked

    private void parcelsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parcelsButtonMouseClicked
        autocampTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_parcelsButtonMouseClicked

    private void reservationsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationsButtonMouseClicked
        autocampTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_reservationsButtonMouseClicked

    private void guestFilterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestFilterButtonMouseClicked
        ((GuestsTableModel) guestTable.getModel()).filterGuests(guestFilterField.getText());
    }//GEN-LAST:event_guestFilterButtonMouseClicked

    private void guestDeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestDeleteButtonMouseClicked
        try {
            ((GuestsTableModel) guestTable.getModel()).deleteGuest(guestTable.getSelectedRows());
        } catch (InterruptedException | ExecutionException | DBInteractionException ex) {
            JOptionPane.showMessageDialog(this, LocalizationWizard.getString("Delete_guest")
                    + LocalizationWizard.getString("Log_file_info"));
            logger.error(ex.getMessage());
        }
    }//GEN-LAST:event_guestDeleteButtonMouseClicked

    private void guestCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestCreateButtonActionPerformed

    }//GEN-LAST:event_guestCreateButtonActionPerformed

    private void parcelFilterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parcelFilterButtonMouseClicked
        ((ParcelsTableModel) parcelTable.getModel()).filterParcels(parcelFilterField.getText());
    }//GEN-LAST:event_parcelFilterButtonMouseClicked

    private void parcelDeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parcelDeleteButtonMouseClicked
        try {
            ((ParcelsTableModel) parcelTable.getModel()).deleteParcel(parcelTable.getSelectedRows());
        } catch (InterruptedException | ExecutionException | DBInteractionException ex) {
            JOptionPane.showMessageDialog(this, LocalizationWizard.getString("Delete_parcel")
                    + LocalizationWizard.getString("Log_file_info"));
            logger.error(ex.getMessage());
        }
    }//GEN-LAST:event_parcelDeleteButtonMouseClicked

    private void reservationDeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationDeleteButtonMouseClicked
        try {
            ((ReservationsTableModel) reservationTable.getModel()).deleteReservation(reservationTable.getSelectedRows());
        } catch (InterruptedException | ExecutionException | DBInteractionException ex) {
            JOptionPane.showMessageDialog(this, LocalizationWizard.getString("Delete_reservation")
                    + LocalizationWizard.getString("Log_file_info"));
            logger.error(ex.getMessage());
        }
    }//GEN-LAST:event_reservationDeleteButtonMouseClicked

    private void reservationFilterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationFilterButtonMouseClicked
        ((ReservationsTableModel) reservationTable.getModel()).filterReservations(reservationFilterField.getText());
    }//GEN-LAST:event_reservationFilterButtonMouseClicked

    private void reservationsCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationsCreateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationsCreateButtonActionPerformed

    private void parcelFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcelFilterButtonActionPerformed

    }//GEN-LAST:event_parcelFilterButtonActionPerformed

    private void guestCreateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestCreateButtonMouseClicked
        try {
            ((GuestsTableModel) guestTable.getModel()).createGuest(
                    guestFullNameField.getText(),
                    guestPhoneField.getText());
            guestFullNameField.setText(null);
            guestPhoneField.setText(null);
        } catch (InterruptedException | ExecutionException ex) {
            AutoCampMenu.jOptionPane.showMessageDialog(this, LocalizationWizard.getString("Create_guest")
                    + LocalizationWizard.getString("Log_file_info"));
            logger.error(ex.getMessage());
        }
    }//GEN-LAST:event_guestCreateButtonMouseClicked

    private void reservationParcelFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationParcelFieldMouseClicked
    }//GEN-LAST:event_reservationParcelFieldMouseClicked

    private void parcelFilterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcelFilterFieldActionPerformed

    }//GEN-LAST:event_parcelFilterFieldActionPerformed

    private void reservationParcelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationParcelButtonMouseClicked
        ParcelSelectPopup parcelPopup = new ParcelSelectPopup(this, rootPaneCheckingEnabled,
                reservationsDateFromChooser.getDate(),
                reservationsDateToChooser.getDate(),
                reservationParcelField);
        parcelPopup.setVisible(true);
    }//GEN-LAST:event_reservationParcelButtonMouseClicked

    private void reservationGuestButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationGuestButtonMouseClicked
        GuestSelectPopup parcelPopup = new GuestSelectPopup(this, rootPaneCheckingEnabled,
                reservationGuestField);
        parcelPopup.setVisible(true);
    }//GEN-LAST:event_reservationGuestButtonMouseClicked

    private void reservationsCreateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationsCreateButtonMouseClicked
        try {
            ((ReservationsTableModel) reservationTable.getModel()).createReservation(
                    reservationsDateFromChooser.getDate(),
                    reservationsDateToChooser.getDate(),
                    Long.parseLong(reservationGuestField.getToolTipText()),
                    Long.parseLong(reservationParcelField.getToolTipText()));

            reservationsDateFromChooser.setDate(null);
            reservationsDateToChooser.setDate(null);
            reservationGuestField.setText(null);
            reservationParcelField.setText(null);
        } catch (InterruptedException | ExecutionException ex) {
            AutoCampMenu.jOptionPane.showMessageDialog(this, LocalizationWizard.getString("Create_reservation")
                    + LocalizationWizard.getString("Log_file_info"));
            logger.error(ex.getMessage());
        }

    }//GEN-LAST:event_reservationsCreateButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoCampMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoCampMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoCampMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoCampMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoCampMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Reservations;
    private javax.swing.JTabbedPane autocampTabbedPane;
    private javax.swing.JButton guestCreateButton;
    private javax.swing.JButton guestDeleteButton;
    private javax.swing.JButton guestFilterButton;
    private javax.swing.JTextField guestFilterField;
    private javax.swing.JLabel guestFilterLabel;
    private javax.swing.JTextField guestFullNameField;
    private javax.swing.JLabel guestFullNameLabel;
    private javax.swing.JTextField guestPhoneField;
    private javax.swing.JLabel guestPhoneLabel;
    private javax.swing.JTable guestTable;
    private javax.swing.JScrollPane guestTablePanel;
    private javax.swing.JButton guestsButton;
    private javax.swing.JPanel guestsTab;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton parcelCreateButton;
    private javax.swing.JButton parcelDeleteButton;
    private javax.swing.JCheckBox parcelElectricityCheckBox;
    private javax.swing.JButton parcelFilterButton;
    private javax.swing.JTextField parcelFilterField;
    private javax.swing.JLabel parcelFilterLabel;
    private javax.swing.JTextField parcelLocationField;
    private javax.swing.JLabel parcelLocationLabel;
    private javax.swing.JLabel parcelResourcesLabel;
    private javax.swing.JTable parcelTable;
    private javax.swing.JScrollPane parcelTablePanel;
    private javax.swing.JCheckBox parcelWaterCheckBox;
    private javax.swing.JButton parcelsButton;
    private javax.swing.JPanel parcelsTab;
    private javax.swing.JButton reservationDeleteButton;
    private javax.swing.JButton reservationFilterButton;
    private javax.swing.JTextField reservationFilterField;
    private javax.swing.JLabel reservationFilterLabel;
    private javax.swing.JButton reservationGuestButton;
    private javax.swing.JTextField reservationGuestField;
    private javax.swing.JLabel reservationGuestLabel;
    private javax.swing.JButton reservationParcelButton;
    private javax.swing.JTextField reservationParcelField;
    private javax.swing.JLabel reservationParcelLabel;
    private javax.swing.JTable reservationTable;
    private javax.swing.JButton reservationsButton;
    private javax.swing.JButton reservationsCreateButton;
    private com.toedter.calendar.JDateChooser reservationsDateFromChooser;
    private com.toedter.calendar.JDateChooser reservationsDateToChooser;
    private javax.swing.JLabel reservationsFromLabel;
    private javax.swing.JScrollPane reservationsScrollPane;
    private javax.swing.JLabel reservationsToLabel;
    // End of variables declaration//GEN-END:variables

    public JDateChooser getReservationsDateFromChooser() {
        return reservationsDateFromChooser;
    }

    public JDateChooser getReservationsDateToChooser() {
        return reservationsDateToChooser;
    }

}
