/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.project.autocamp.gui;

import cz.muni.fi.pv168.project.autocamp.Parcel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Administrator
 */
public class AutoCampMenu extends javax.swing.JFrame {

    /**
     * Creates new form AutoCampMenu
     */
    public AutoCampMenu() {
        initComponents();
        GuestsTableModel guestsModel = (GuestsTableModel) guestTable.getModel();
        ParcelsTableModel parcelsModel = (ParcelsTableModel) parcelTable.getModel();
        ReservationsTableModel reservationsModel = (ReservationsTableModel) reservationsTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        reservationsButton = new javax.swing.JButton();
        guestsButton = new javax.swing.JButton();
        parcelsButton = new javax.swing.JButton();
        autocampTabbedPane = new javax.swing.JTabbedPane();
        guestsTab = new javax.swing.JPanel();
        guestTablePanel = new javax.swing.JScrollPane();
        guestTable = new javax.swing.JTable();
        guestCreateButton = new javax.swing.JButton();
        guestPhoneField = new javax.swing.JTextField();
        guestFullNameField = new javax.swing.JTextField();
        guestFullNameLabel = new javax.swing.JLabel();
        guestPhoneLabel = new javax.swing.JLabel();
        guestFilterButton = new javax.swing.JButton();
        guestDeleteButton = new javax.swing.JButton();
        guestFilterField = new javax.swing.JTextField();
        guestFilterLabel = new javax.swing.JLabel();
        parcelsTab = new javax.swing.JPanel();
        parcelTablePanel = new javax.swing.JScrollPane();
        parcelTable = new javax.swing.JTable();
        parcelCreateButton = new javax.swing.JButton();
        parcelLocationField = new javax.swing.JTextField();
        parcelLocationLabel = new javax.swing.JLabel();
        parcelFilterField = new javax.swing.JTextField();
        parcelFilterButton = new javax.swing.JButton();
        parcelElectricityCheckBox = new javax.swing.JCheckBox();
        parcelWaterCheckBox = new javax.swing.JCheckBox();
        parcelResourcesLabel = new javax.swing.JLabel();
        parcelFilterLabel = new javax.swing.JLabel();
        parcelDeleteButton = new javax.swing.JButton();
        Reservations = new javax.swing.JPanel();
        reservationsScrollPane = new javax.swing.JScrollPane();
        reservationsTable = new javax.swing.JTable();
        reservationsCreateButton = new javax.swing.JButton();
        reservationsFromLabel = new javax.swing.JLabel();
        reservationsFilterField = new javax.swing.JTextField();
        reservationsFilterButton = new javax.swing.JButton();
        reservationsToLabel = new javax.swing.JLabel();
        reservationsParcelField = new javax.swing.JTextField();
        reservationsParcelLabel = new javax.swing.JLabel();
        reservationsGuestField = new javax.swing.JTextField();
        reservationsGuestLabel = new javax.swing.JLabel();
        reservationsDateFromChooser = new com.toedter.calendar.JDateChooser();
        reservationsDateToChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        leftPanel.setBackground(new java.awt.Color(204, 204, 204));
        leftPanel.setFocusable(false);
        leftPanel.setMaximumSize(new java.awt.Dimension(207, 32767));

        reservationsButton.setBackground(new java.awt.Color(255, 255, 255));
        reservationsButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        reservationsButton.setText("Reservations");
        reservationsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationsButtonMouseClicked(evt);
            }
        });

        guestsButton.setBackground(new java.awt.Color(255, 255, 255));
        guestsButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        guestsButton.setText("Guests");
        guestsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guestsButtonMouseClicked(evt);
            }
        });

        parcelsButton.setBackground(new java.awt.Color(255, 255, 255));
        parcelsButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        parcelsButton.setText("Parcels");
        parcelsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parcelsButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservationsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guestsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parcelsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parcelsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(leftPanel);

        autocampTabbedPane.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        autocampTabbedPane.setToolTipText("");

        guestTable.setModel(new GuestsTableModel() );
        guestTablePanel.setViewportView(guestTable);

        guestCreateButton.setText("Create");
        guestCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestCreateButtonActionPerformed(evt);
            }
        });

        guestFullNameLabel.setText("Full name:");

        guestPhoneLabel.setText("Phone:");

        guestFilterButton.setText("Filter");
        guestFilterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guestFilterButtonMouseClicked(evt);
            }
        });

        guestDeleteButton.setText("Delete selected");
        guestDeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guestDeleteButtonMouseClicked(evt);
            }
        });

        guestFilterLabel.setText("Filter:");

        javax.swing.GroupLayout guestsTabLayout = new javax.swing.GroupLayout(guestsTab);
        guestsTab.setLayout(guestsTabLayout);
        guestsTabLayout.setHorizontalGroup(
            guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guestTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
            .addGroup(guestsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(guestFilterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guestPhoneLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                    .addComponent(guestFullNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, guestsTabLayout.createSequentialGroup()
                        .addComponent(guestFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guestFilterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(guestPhoneField)
                    .addComponent(guestFullNameField, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guestDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(guestCreateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        guestsTabLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {guestFilterLabel, guestPhoneLabel});

        guestsTabLayout.setVerticalGroup(
            guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guestsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(guestsTabLayout.createSequentialGroup()
                        .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guestFullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guestFullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guestPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guestPhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(guestCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(guestFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(guestFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(guestFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(guestDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guestTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
        );

        autocampTabbedPane.addTab("Guests", guestsTab);

        parcelTable.setModel(new ParcelsTableModel());
        parcelTablePanel.setViewportView(parcelTable);

        parcelCreateButton.setText("Create");
        parcelCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcelCreateButtonActionPerformed(evt);
            }
        });

        parcelLocationLabel.setText("Location:");

        parcelFilterButton.setText("Filter");
        parcelFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcelFilterButtonActionPerformed(evt);
            }
        });

        parcelElectricityCheckBox.setText("Electricity");

        parcelWaterCheckBox.setText("Water");

        parcelResourcesLabel.setText("Resources:");

        parcelFilterLabel.setText("Filter:");

        parcelDeleteButton.setText("Delete selected");
        parcelDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcelDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout parcelsTabLayout = new javax.swing.GroupLayout(parcelsTab);
        parcelsTab.setLayout(parcelsTabLayout);
        parcelsTabLayout.setHorizontalGroup(
            parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parcelTablePanel)
            .addGroup(parcelsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parcelFilterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parcelLocationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parcelResourcesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parcelLocationField)
                    .addGroup(parcelsTabLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(parcelElectricityCheckBox)
                        .addGap(115, 115, 115)
                        .addComponent(parcelWaterCheckBox))
                    .addGroup(parcelsTabLayout.createSequentialGroup()
                        .addComponent(parcelFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parcelFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parcelCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parcelDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        parcelsTabLayout.setVerticalGroup(
            parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parcelsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parcelCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(parcelsTabLayout.createSequentialGroup()
                        .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parcelLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parcelLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parcelResourcesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parcelElectricityCheckBox)
                            .addComponent(parcelWaterCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parcelFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(parcelsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(parcelFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(parcelFilterField)
                                .addComponent(parcelDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(parcelTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );

        autocampTabbedPane.addTab("Parcels", parcelsTab);

        reservationsTable.setModel(new ReservationsTableModel());
        reservationsScrollPane.setViewportView(reservationsTable);

        reservationsCreateButton.setText("Create");
        reservationsCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationsCreateButtonActionPerformed(evt);
            }
        });

        reservationsFromLabel.setText("From:");

        reservationsFilterButton.setText("Filter");

        reservationsToLabel.setText("To:");

        reservationsParcelLabel.setText("Parcel:");

        reservationsGuestLabel.setText("Guest:");

        reservationsDateFromChooser.setDateFormatString("yyyy-MM-dd");

        reservationsDateToChooser.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout ReservationsLayout = new javax.swing.GroupLayout(Reservations);
        Reservations.setLayout(ReservationsLayout);
        ReservationsLayout.setHorizontalGroup(
            ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reservationsScrollPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReservationsLayout.createSequentialGroup()
                        .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReservationsLayout.createSequentialGroup()
                                .addComponent(reservationsFromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reservationsDateFromChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                            .addGroup(ReservationsLayout.createSequentialGroup()
                                .addComponent(reservationsGuestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reservationsGuestField)))
                        .addGap(35, 35, 35)
                        .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reservationsToLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reservationsParcelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reservationsDateToChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addGroup(ReservationsLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(reservationsParcelField, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))))
                    .addComponent(reservationsFilterField))
                .addGap(21, 21, 21)
                .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservationsCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservationsFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        ReservationsLayout.setVerticalGroup(
            ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReservationsLayout.createSequentialGroup()
                        .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reservationsToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservationsDateToChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservationsDateFromChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservationsFromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reservationsGuestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservationsGuestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservationsParcelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservationsParcelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(reservationsCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reservationsFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservationsFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reservationsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))
        );

        autocampTabbedPane.addTab("Reservations", Reservations);

        getContentPane().add(autocampTabbedPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parcelCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcelCreateButtonActionPerformed
        Parcel parcel = new Parcel();
        parcel.setLocation(parcelLocationField.getText());
        parcel.setWithElectricity(parcelElectricityCheckBox.isSelected());
        parcel.setWithWater(parcelWaterCheckBox.isSelected());
        ((ParcelsTableModel) parcelTable.getModel()).createParcel(parcel);
        parcelLocationField.setText(null);
        parcelElectricityCheckBox.setSelected(false);
        parcelWaterCheckBox.setSelected(false);
    }//GEN-LAST:event_parcelCreateButtonActionPerformed

    private void guestsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestsButtonMouseClicked
        autocampTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_guestsButtonMouseClicked

    private void parcelsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parcelsButtonMouseClicked
        autocampTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_parcelsButtonMouseClicked

    private void reservationsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationsButtonMouseClicked
        autocampTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_reservationsButtonMouseClicked

    private void reservationsCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationsCreateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationsCreateButtonActionPerformed

    private void guestFilterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestFilterButtonMouseClicked
        ((GuestsTableModel) guestTable.getModel()).filterTable(guestFilterField.getText());
    }//GEN-LAST:event_guestFilterButtonMouseClicked

    private void guestDeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestDeleteButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_guestDeleteButtonMouseClicked

    private void parcelDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcelDeleteButtonActionPerformed
        int[] rows = parcelTable.getSelectedRows();
        ParcelsTableModel tableModel = (ParcelsTableModel) parcelTable.getModel();
        List<Parcel> parcels = new ArrayList<>();
        for (int i = 0; i < rows.length; i++) {
            parcels.add(tableModel.getParcels().get(rows[i]));
        }
        tableModel.deleteParcel(parcels);
    }//GEN-LAST:event_parcelDeleteButtonActionPerformed

    private void parcelFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcelFilterButtonActionPerformed
        ((ParcelsTableModel) parcelTable.getModel()).filterParcels(parcelFilterField.getText());
    }//GEN-LAST:event_parcelFilterButtonActionPerformed

    private void guestCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestCreateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guestCreateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoCampMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoCampMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoCampMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoCampMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoCampMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Reservations;
    private javax.swing.JTabbedPane autocampTabbedPane;
    private javax.swing.JButton guestCreateButton;
    private javax.swing.JButton guestDeleteButton;
    private javax.swing.JButton guestFilterButton;
    private javax.swing.JTextField guestFilterField;
    private javax.swing.JLabel guestFilterLabel;
    private javax.swing.JTextField guestFullNameField;
    private javax.swing.JLabel guestFullNameLabel;
    private javax.swing.JTextField guestPhoneField;
    private javax.swing.JLabel guestPhoneLabel;
    private javax.swing.JTable guestTable;
    private javax.swing.JScrollPane guestTablePanel;
    private javax.swing.JButton guestsButton;
    private javax.swing.JPanel guestsTab;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton parcelCreateButton;
    private javax.swing.JButton parcelDeleteButton;
    private javax.swing.JCheckBox parcelElectricityCheckBox;
    private javax.swing.JButton parcelFilterButton;
    private javax.swing.JTextField parcelFilterField;
    private javax.swing.JLabel parcelFilterLabel;
    private javax.swing.JTextField parcelLocationField;
    private javax.swing.JLabel parcelLocationLabel;
    private javax.swing.JLabel parcelResourcesLabel;
    private javax.swing.JTable parcelTable;
    private javax.swing.JScrollPane parcelTablePanel;
    private javax.swing.JCheckBox parcelWaterCheckBox;
    private javax.swing.JButton parcelsButton;
    private javax.swing.JPanel parcelsTab;
    private javax.swing.JButton reservationsButton;
    private javax.swing.JButton reservationsCreateButton;
    private com.toedter.calendar.JDateChooser reservationsDateFromChooser;
    private com.toedter.calendar.JDateChooser reservationsDateToChooser;
    private javax.swing.JButton reservationsFilterButton;
    private javax.swing.JTextField reservationsFilterField;
    private javax.swing.JLabel reservationsFromLabel;
    private javax.swing.JTextField reservationsGuestField;
    private javax.swing.JLabel reservationsGuestLabel;
    private javax.swing.JTextField reservationsParcelField;
    private javax.swing.JLabel reservationsParcelLabel;
    private javax.swing.JScrollPane reservationsScrollPane;
    private javax.swing.JTable reservationsTable;
    private javax.swing.JLabel reservationsToLabel;
    // End of variables declaration//GEN-END:variables
}
