/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cz.muni.fi.pv168.project.autocamp.gui;

import java.awt.*;
import java.awt.event.*;
import java.awt.event.MouseEvent;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.table.*;

/**
 *
 * @author Administrator
 */
public class MainMenu extends javax.swing.JFrame {

    /** Creates new form MainMenu */
    private void ReservationsButtonMouseClicked(MouseEvent e) {
        // TODO add your code here
    }

    private void ReservationsButtonActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void GuestsButtonMouseClicked(MouseEvent e) {
        // TODO add your code here
    }

    private void GuestsButtonActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void ParcelsButtonMouseClicked(MouseEvent e) {
        // TODO add your code here
    }

    private void ParcelsButtonActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void GuestCreateButtonActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void GuestPhoneFieldActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void GuestFullNameFieldActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void GuestFilterFieldActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void GuestFilterButtonActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void ParcelCreateButtonActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void ParcelLocationFieldActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void ParcelFilterFieldActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void ParcelFilterButtonActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void ReservationsCreateButtonActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void ReservationsFromFieldActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void ReservationsFilterFieldActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void ReservationsFilterButtonActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void ReservationsToFieldActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void ReservationsParcelFieldActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void ReservationsGuestFieldActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    public MainMenu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ReservationsButton = new javax.swing.JButton();
        GuestsButton = new javax.swing.JButton();
        ParcelsButton = new javax.swing.JButton();
        autocampTabbedPane = new javax.swing.JTabbedPane();
        Parcels = new javax.swing.JPanel();
        ParcelScrollPane = new javax.swing.JScrollPane();
        ParcelTable = new javax.swing.JTable();
        ParcelCreateButton = new javax.swing.JButton();
        ParcelLocationField = new javax.swing.JTextField();
        ParcelLocationLabel = new javax.swing.JLabel();
        ParcelFilterField = new javax.swing.JTextField();
        ParcelFilterButton = new javax.swing.JButton();
        ParcelElectricityCheckBox = new javax.swing.JCheckBox();
        ParcelWaterCheckBox = new javax.swing.JCheckBox();
        ParcelResourcesLabel = new javax.swing.JLabel();
        Reservations = new javax.swing.JPanel();
        ReservationsScrollPane = new javax.swing.JScrollPane();
        ReservationsTable = new javax.swing.JTable();
        ReservationsCreateButton = new javax.swing.JButton();
        ReservationsFromField = new javax.swing.JTextField();
        ReservationsFromLabel = new javax.swing.JLabel();
        ReservationsFilterField = new javax.swing.JTextField();
        ReservationsFilterButton = new javax.swing.JButton();
        ReservationsToLabel = new javax.swing.JLabel();
        ReservationsToField = new javax.swing.JTextField();
        ReservationsParcelField = new javax.swing.JTextField();
        ReservationsParcelLabel = new javax.swing.JLabel();
        ReservationsGuestField = new javax.swing.JTextField();
        ReservationsGuestLabel = new javax.swing.JLabel();
        Guests = new javax.swing.JPanel();
        GuestTablePanel = new javax.swing.JScrollPane();
        GuestTable = new javax.swing.JTable();
        GuestCreateButton = new javax.swing.JButton();
        GuestPhoneField = new javax.swing.JTextField();
        GuestFullNameField = new javax.swing.JTextField();
        GuestFullNameLabel = new javax.swing.JLabel();
        GuestPhoneLabel = new javax.swing.JLabel();
        GuestFilterField = new javax.swing.JTextField();
        GuestFilterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setFocusable(false);

        ReservationsButton.setBackground(new java.awt.Color(255, 255, 255));
        ReservationsButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        ReservationsButton.setText("Reservations");

        GuestsButton.setBackground(new java.awt.Color(255, 255, 255));
        GuestsButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        GuestsButton.setText("Guests");

        ParcelsButton.setBackground(new java.awt.Color(255, 255, 255));
        ParcelsButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        ParcelsButton.setText("Parcels");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReservationsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GuestsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(ParcelsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GuestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ParcelsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReservationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        autocampTabbedPane.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        autocampTabbedPane.setToolTipText("");

        ParcelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Location", "Electiricty", "Water", "Delete"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ParcelScrollPane.setViewportView(ParcelTable);
        if (ParcelTable.getColumnModel().getColumnCount() > 0) {
            ParcelTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            ParcelTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            ParcelTable.getColumnModel().getColumn(2).setPreferredWidth(150);
            ParcelTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            ParcelTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        ParcelCreateButton.setText("Create");

        ParcelLocationLabel.setText("Location:");

        ParcelFilterButton.setText("Filter");

        ParcelElectricityCheckBox.setText("Electricity");

        ParcelWaterCheckBox.setText("Water");

        ParcelResourcesLabel.setText("Resources:");

        javax.swing.GroupLayout ParcelsLayout = new javax.swing.GroupLayout(Parcels);
        Parcels.setLayout(ParcelsLayout);
        ParcelsLayout.setHorizontalGroup(
            ParcelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParcelScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
            .addGroup(ParcelsLayout.createSequentialGroup()
                .addGroup(ParcelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ParcelFilterField)
                    .addGroup(ParcelsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ParcelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ParcelLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ParcelResourcesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(ParcelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ParcelsLayout.createSequentialGroup()
                                .addComponent(ParcelElectricityCheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(ParcelWaterCheckBox)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ParcelLocationField))))
                .addGap(18, 18, 18)
                .addGroup(ParcelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ParcelCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ParcelFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ParcelsLayout.setVerticalGroup(
            ParcelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParcelsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ParcelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ParcelsLayout.createSequentialGroup()
                        .addGroup(ParcelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ParcelLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ParcelLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ParcelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ParcelElectricityCheckBox)
                            .addComponent(ParcelWaterCheckBox)
                            .addComponent(ParcelResourcesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ParcelCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ParcelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ParcelFilterField)
                    .addComponent(ParcelFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ParcelScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
        );

        autocampTabbedPane.addTab("Parcels", Parcels);

        ReservationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "From", "To", "Guest", "Parcel", "Delete"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ReservationsScrollPane.setViewportView(ReservationsTable);
        if (ReservationsTable.getColumnModel().getColumnCount() > 0) {
            ReservationsTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            ReservationsTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            ReservationsTable.getColumnModel().getColumn(2).setPreferredWidth(150);
            ReservationsTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            ReservationsTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        ReservationsCreateButton.setText("Create");

        ReservationsFromLabel.setText("From:");

        ReservationsFilterButton.setText("Filter");

        ReservationsToLabel.setText("To:");

        ReservationsParcelLabel.setText("Parcel:");

        ReservationsGuestLabel.setText("Guest:");

        javax.swing.GroupLayout ReservationsLayout = new javax.swing.GroupLayout(Reservations);
        Reservations.setLayout(ReservationsLayout);
        ReservationsLayout.setHorizontalGroup(
            ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReservationsScrollPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservationsLayout.createSequentialGroup()
                .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ReservationsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ReservationsGuestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReservationsGuestField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ReservationsParcelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReservationsParcelField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ReservationsFilterField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ReservationsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ReservationsFromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReservationsFromField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ReservationsToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReservationsToField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReservationsCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReservationsFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ReservationsLayout.setVerticalGroup(
            ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ReservationsLayout.createSequentialGroup()
                        .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReservationsFromField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReservationsFromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReservationsToField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReservationsToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReservationsGuestField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReservationsGuestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReservationsParcelField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReservationsParcelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ReservationsCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReservationsFilterField)
                    .addComponent(ReservationsFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReservationsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
        );

        autocampTabbedPane.addTab("Reservations", Reservations);

        GuestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Full Name", "Phone", "Delete"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GuestTablePanel.setViewportView(GuestTable);
        if (GuestTable.getColumnModel().getColumnCount() > 0) {
            GuestTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            GuestTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            GuestTable.getColumnModel().getColumn(2).setResizable(false);
            GuestTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            GuestTable.getColumnModel().getColumn(2).setHeaderValue("Phone");
            GuestTable.getColumnModel().getColumn(3).setResizable(false);
            GuestTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            GuestTable.getColumnModel().getColumn(3).setHeaderValue("Delete");
        }

        GuestCreateButton.setText("Create");

        GuestFullNameLabel.setText("Full name:");

        GuestPhoneLabel.setText("Phone:");

        GuestFilterButton.setText("Filter");

        javax.swing.GroupLayout GuestsLayout = new javax.swing.GroupLayout(Guests);
        Guests.setLayout(GuestsLayout);
        GuestsLayout.setHorizontalGroup(
            GuestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GuestTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
            .addGroup(GuestsLayout.createSequentialGroup()
                .addGroup(GuestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GuestsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(GuestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(GuestPhoneLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GuestFullNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(GuestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GuestPhoneField)
                            .addComponent(GuestFullNameField)))
                    .addComponent(GuestFilterField))
                .addGap(18, 18, 18)
                .addGroup(GuestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GuestCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuestFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        GuestsLayout.setVerticalGroup(
            GuestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GuestsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GuestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(GuestsLayout.createSequentialGroup()
                        .addGroup(GuestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GuestFullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuestFullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GuestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GuestPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuestPhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(GuestCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GuestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GuestFilterField)
                    .addComponent(GuestFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GuestTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
        );

        autocampTabbedPane.addTab("Guests", Guests);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autocampTabbedPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(autocampTabbedPane)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuestCreateButton;
    private javax.swing.JButton GuestFilterButton;
    private javax.swing.JTextField GuestFilterField;
    private javax.swing.JTextField GuestFullNameField;
    private javax.swing.JLabel GuestFullNameLabel;
    private javax.swing.JTextField GuestPhoneField;
    private javax.swing.JLabel GuestPhoneLabel;
    private javax.swing.JTable GuestTable;
    private javax.swing.JScrollPane GuestTablePanel;
    private javax.swing.JPanel Guests;
    private javax.swing.JButton GuestsButton;
    private javax.swing.JButton ParcelCreateButton;
    private javax.swing.JCheckBox ParcelElectricityCheckBox;
    private javax.swing.JButton ParcelFilterButton;
    private javax.swing.JTextField ParcelFilterField;
    private javax.swing.JTextField ParcelLocationField;
    private javax.swing.JLabel ParcelLocationLabel;
    private javax.swing.JLabel ParcelResourcesLabel;
    private javax.swing.JScrollPane ParcelScrollPane;
    private javax.swing.JTable ParcelTable;
    private javax.swing.JCheckBox ParcelWaterCheckBox;
    private javax.swing.JPanel Parcels;
    private javax.swing.JButton ParcelsButton;
    private javax.swing.JPanel Reservations;
    private javax.swing.JButton ReservationsButton;
    private javax.swing.JButton ReservationsCreateButton;
    private javax.swing.JButton ReservationsFilterButton;
    private javax.swing.JTextField ReservationsFilterField;
    private javax.swing.JTextField ReservationsFromField;
    private javax.swing.JLabel ReservationsFromLabel;
    private javax.swing.JTextField ReservationsGuestField;
    private javax.swing.JLabel ReservationsGuestLabel;
    private javax.swing.JTextField ReservationsParcelField;
    private javax.swing.JLabel ReservationsParcelLabel;
    private javax.swing.JScrollPane ReservationsScrollPane;
    private javax.swing.JTable ReservationsTable;
    private javax.swing.JTextField ReservationsToField;
    private javax.swing.JLabel ReservationsToLabel;
    private javax.swing.JTabbedPane autocampTabbedPane;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
