/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.project.autocamp.gui;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Administrator
 */
public class ParcelSelectPopup extends javax.swing.JDialog {

    private LocalDate from;
    private LocalDate to;

    /**
     * Creates new form ParcelSelectPop
     */
    public ParcelSelectPopup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.from = LocalDate.MIN;
        this.to = LocalDate.MAX;
    }

    public ParcelSelectPopup(java.awt.Frame parent, boolean modal, String from, String to) {
        super(parent, modal);
        initComponents();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        this.from = LocalDate.parse((CharSequence) from, dtf);
        this.to = LocalDate.parse((CharSequence) to, dtf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parcelSelectFilterField = new javax.swing.JTextField();
        parcelSelectFilterLabel = new javax.swing.JLabel();
        parcelSelectTablePanel = new javax.swing.JScrollPane();
        parcelSelectTable = new javax.swing.JTable();
        parcelSelectFilterButton = new javax.swing.JButton();
        parceSelectDeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        parcelSelectFilterLabel.setText(LocalizationWizard.getString("Filter_label"));

        parcelSelectTable.setModel(new ParcelSelectPopupTableModel(from, to));
        parcelSelectTablePanel.setViewportView(parcelSelectTable);

        parcelSelectFilterButton.setText(LocalizationWizard.getString("Filter"));
        parcelSelectFilterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parcelSelectFilterButtonMouseClicked(evt);
            }
        });
        parcelSelectFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcelSelectFilterButtonActionPerformed(evt);
            }
        });

        parceSelectDeleteButton.setText(LocalizationWizard.getString("Select"));
        parceSelectDeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parceSelectDeleteButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 832, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(parcelSelectTablePanel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(parcelSelectFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parcelSelectFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(parcelSelectFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(parceSelectDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(parcelSelectFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parceSelectDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parcelSelectFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parcelSelectFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(parcelSelectTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parcelSelectFilterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parcelSelectFilterButtonMouseClicked
        ((ParcelsTableModel) parcelSelectTable.getModel()).filterParcels(parcelSelectFilterField.getText());
    }//GEN-LAST:event_parcelSelectFilterButtonMouseClicked

    private void parcelSelectFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcelSelectFilterButtonActionPerformed

    }//GEN-LAST:event_parcelSelectFilterButtonActionPerformed

    private void parceSelectDeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parceSelectDeleteButtonMouseClicked
        ((ParcelsTableModel) parcelSelectTable.getModel()).deleteParcel(parcelSelectTable.getSelectedRows());
    }//GEN-LAST:event_parceSelectDeleteButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParcelSelectPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParcelSelectPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParcelSelectPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParcelSelectPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ParcelSelectPopup dialog = new ParcelSelectPopup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton parceSelectDeleteButton;
    private javax.swing.JButton parcelSelectFilterButton;
    private javax.swing.JTextField parcelSelectFilterField;
    private javax.swing.JLabel parcelSelectFilterLabel;
    private javax.swing.JTable parcelSelectTable;
    private javax.swing.JScrollPane parcelSelectTablePanel;
    // End of variables declaration//GEN-END:variables
}
